In [34]:
import pandas as pd
data=pd.read_csv("data.csv",sep="\t",encoding="utf-8")

In [35]:
data

,title,etime,content,vote,comment
0,낼 역학 쪽지시험 보는건가요??,방금,이번 주에 본다고 하셨던거 같은데 내일인지 수요일인지 모르겠어요,0,0
1,투자론 대박임,3분 전,ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 하...,0,4
2,😡길거리에서 담배 피면 무적권 벌금,4분 전,"100,000원씩 물리면 안되나???간접흡연 너무 시러...ㅜㅜ 특히 아침에 집 나...",1,2
3,독문산,6분 전,듣는사람??,0,1
4,지금 사캠 과제 제출잘돼??,6분 전,나만 안돼?……🥹,0,0
...,...,...,...,...,...
595,셤기간에 볼링 딱 한판만 같이 칠 사람,10/22 18:07,아무나 구함,0,2
596,컴입 ㅎㅎㅇ 교수님 과제 도와주세요ㅠㅠ,10/22 18:06,과제7 하는데 너무 모르겠어요 도와주실 분..ㅜㅜ,0,1
597,일선 사이트,10/22 18:05,시험인데 안들어 가지는데 이거 어떡하냐 진짜 미치겠다ㅠㅠㅠㅠ,0,11
598,의류학과를 우습게 보고있네,10/22 18:04,용서 못해,0,2
599,학점교류 시험인데,10/22 18:03,사이트 터지면 우째치라고...,0,5

In [36]:

import datetime

d=datetime.datetime.now()-datetime.timedelta(seconds=30*60)
d.strftime('%Y/%m/%d %H:%M')

'2022/10/23 22:10'

In [37]:
data['etime']

0               방금
1             3분 전
2             4분 전
3             6분 전
4             6분 전
          ...
595    10/22 18:07
596    10/22 18:06
597    10/22 18:05
598    10/22 18:04
599    10/22 18:03
Name: etime, Length: 600, dtype: object

In [41]:
for idx, t in enumerate(data['etime']):
    if "분" in t:
        temp = t.split("분")
        d = datetime.datetime.now()-datetime.timedelta(seconds=int(temp[0])*60)
        data["etime"][idx] = d.strftime('%Y/%m/%d %H:%M')
    elif "방금" in t:
        d = datetime.datetime.now()
        data["etime"][idx]=d.strftime('%Y/%m/%d %H:%M') 
    elif len(t)<12:
        data["etime"][idx] = "2022/"+data["etime"][idx]

TypeError: argument of type 'datetime.datetime' is not iterable

In [39]:
len(data["etime"][500])

16

In [40]:
data

,title,etime,content,vote,comment
0,낼 역학 쪽지시험 보는건가요??,2022-10-23 22:40:16.626577,이번 주에 본다고 하셨던거 같은데 내일인지 수요일인지 모르겠어요,0,0
1,투자론 대박임,2022/10/23 22:37,ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 하...,0,4
2,😡길거리에서 담배 피면 무적권 벌금,2022/10/23 22:36,"100,000원씩 물리면 안되나???간접흡연 너무 시러...ㅜㅜ 특히 아침에 집 나...",1,2
3,독문산,2022/10/23 22:34,듣는사람??,0,1
4,지금 사캠 과제 제출잘돼??,2022/10/23 22:34,나만 안돼?……🥹,0,0
...,...,...,...,...,...
595,셤기간에 볼링 딱 한판만 같이 칠 사람,2022/10/22 18:07,아무나 구함,0,2
596,컴입 ㅎㅎㅇ 교수님 과제 도와주세요ㅠㅠ,2022/10/22 18:06,과제7 하는데 너무 모르겠어요 도와주실 분..ㅜㅜ,0,1
597,일선 사이트,2022/10/22 18:05,시험인데 안들어 가지는데 이거 어떡하냐 진짜 미치겠다ㅠㅠㅠㅠ,0,11
598,의류학과를 우습게 보고있네,2022/10/22 18:04,용서 못해,0,2
599,학점교류 시험인데,2022/10/22 18:03,사이트 터지면 우째치라고...,0,5